spring.application.name=springbootwebturorial
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file/users/amit/Documents/springbootwebturorial/db
spring.datasource.username=amitDB
spring.datasource.password=Amit123
spring.jpa.hibernate.ddl-auto=update