spring.application.name=springbootwebturorial
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:file/users/amit/Documents/springbootwebturorial/db
spring.datasource.url=jdbc:h2:file:C:/Users/DELL/Documents/springbootwebturorial/db
spring.datasource.username=amitDB
spring.datasource.password=Amit123
spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
